version: '2'
services:
  elasticsearch:
    image: elasticsearch:2
    ports:
      - '127.0.0.1:9200:9200'
      - '127.0.0.1:9300:9300'
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
  kibana:
    image: kibana:4
    ports:
      - 5601:5601
    links:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
