version: '2'
services:
  grafana:
    build: ./grafana
    environment: 
      - GF_SECURITY_ADMIN_PASSWORD
    links:
      - influx
    volumes:
      - ./grafana-data:/usr/share/grafana/data
  influx:
    build: ./influx
    volumes:
      - ./influx-data:/root/.influxdb
      - ./influxdb_backup:/influxdb_backup
