version: '2'
services:
  grafana:
    build: ./grafana
    environment: 
      - GF_SECURITY_ADMIN_PASSWORD
    ports:
      - '3000:3000'
    links:
      - influx
    volumes:
      - ./grafana-data:/usr/share/grafana/data
  influx:
    build: ./influx
    ports:
      - '127.0.0.1:8086:8086'
      - '127.0.0.1:8083:8083'
      - '127.0.0.1:25826:25826'
      - '127.0.0.1:2003:2003'
    volumes:
      - ./influx-data:/root/.influxdb
      - ./influxdb_backup:/influxdb_backup
